version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
     - "3309:3306"
    environment:
     MYSQL_DATABASE: 'fisiosystem'
     MYSQL_ALLOW_EMPTY_PASSWORD: 1
     MYSQL_PASSWORD: ""
  app:
    build:
     context: .
     dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
     - "8081:80"
    volumes:
     - ./:/var/www/html
    